Manage all different options though the config file

diff --git a/ipwarn b/ipwarn
--- a/ipwarn
+++ b/ipwarn
@@ -1,18 +1,17 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 
 print_version(){
     echo "ipwarn 2.0.0"
 }
 
-help(){
+print_help(){
     echo "$(print_version)"
     echo "usage:  ipwarn <flag 1> ... <flag n>"
     echo "flags:"
-    echo "    ipwarn {-h --help}            display the help (this) and exit"
-    echo "    ipwarn {-v -V --version}      display the version and exit"
-    echo "    ipwarn {-t --telegram}        send message via Telegram if the IP has changed"
-    echo "    ipwarn {-g --godaddy}         updates GoDaddy DNS record if the IP has changed"
+    echo "    ipwarn {-h --help}                    display the help (this) and exit"
+    echo "    ipwarn {-v -V --version}              display the version and exit"
+    echo "    ipwarn {-c --config } config-file     choose a custom location for the config file"
 }
 
 telegram(){
@@ -21,35 +20,17 @@ telegram(){
 }
 
 godaddy(){
-    result="$(curl -s -X PUT "https://api.godaddy.com/v1/domains/${GD_DOMAIN}/records/${GD_RECORD_TYPE}/${GD_RECORD_NAME}" -H "Authorization: sso-key ${GD_API_KEY}:${GD_API_SECRET}" -H "Content-Type: application/json" -d "[{\"data\": \"${new_ip}\"}]"
-	echo "GoDaddy record updated")"
+    result="$(curl -s -X PUT "https://api.godaddy.com/v1/domains/${GD_DOMAIN}/records/${GD_RECORD_TYPE}/${GD_RECORD_NAME}" -H "Authorization: sso-key ${GD_API_KEY}:${GD_API_SECRET}" -H "Content-Type: application/json" -d "[{\"data\": \"${new_ip}\"}]")"
+	echo "GoDaddy record updated"
 }
 
-main(){
-    # Check if help is wanted
-    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-        help
-        exit 0
-    fi
-
-    # Check if the user wants the version
-    if [ "$1" = "-v" ] || [ "$1" = "-V" ] || [ "$1" = "--version" ] || [ "$1" = "--help" ]; then
-        print_version
-        exit 0
-    fi
-
-    # Retrieve flags
-    telegram_flag=0
-    godaddy_flag=0
-    time=30
+get_config(){
+    config_file="/etc/ipwarn/ipwarn.conf"
     while [ $# -gt 0 ]; do
         case "$1" in
-            -t|--telegram)
-                telegramFlag=1
+            -c|--config)
                 shift
-                ;;
-            -g|--godaddy)
-                godaddyFlag=1
+                config_file=$1
                 shift
                 ;;
             *)
@@ -57,23 +38,48 @@ main(){
                 ;;
         esac
     done
-    
+    echo $config_file
+    if [ -e "${config_file}" ]; then
+        if ! source "${config_file}"; then
+            echo "error reading or opening config file ${config_file}"
+            exit 1
+        fi
+    else
+        echo "error reading or opening config file ${config_file}"
+        exit 1
+    fi
+}
+
+main(){
+    # Check if help is wanted
+    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+        print_help
+        exit 0
+    fi
+
+    # Check if the user wants the version
+    if [ "$1" = "-v" ] || [ "$1" = "-V" ] || [ "$1" = "--version" ]; then
+        print_version
+        exit 0
+    fi
+
+    get_config "$@"
+
     # Infinite loop that checks if the ip has changed
     while true
     do
         new_ip="$(curl -s icanhazip.com)"
-        source /etc/ipwarn.conf
-        if [ "${new_ip}" != "${IP}" ]; then
-            sed -i -e 's/IP="'"${IP}"'"/IP="'"${new_ip}"'"/g' /etc/ipwarn.conf
+        if [ "${new_ip}" != "${ip}" ]; then
+            ip="${new_ip}"
             echo "New ip is ${new_ip}"
-            if [ "${telegram_flag}" -eq "1" ]; then
+            if [ "$UPDATE_TELEGRAM" = true ]; then
                 telegram
             fi
-            if [ "${godaddy_flag}" -eq "1" ]; then
+            if [ "$UPDATE_GODADDY" = true ]; then
                 godaddy
             fi
         fi
-        sleep "${time}"
+        sleep "${INTERVAL}"
     done
 }
 
